service: yandex-cloud-nodejs
name: yandex-cloud-template
frameworkVersion: ">2.0.0"

provider:
  name: yandex-cloud
  runtime: nodejs16

plugins:
  - serverless-yandex-cloud

package:
  exclude:
    - ./**
  include:
    - ./dist/*.js
    - ./package.json
    - ./package-lock.json

functions:
  simple:
    handler: index.hello
    memory: 128
    timeout: 5
    account: function-sa

  timer:
    handler: index.hello
    memory: 128
    timeout: 5
    events:
      - cron:
          expression: "* * * * ? *"
          account: trigger-sa
          retry:
            attempts: 1
            interval: 10

resources:
  trigger-sa:
    type: yc::ServiceAccount
    roles:
      - serverless.functions.invoker
  function-sa:
    type: yc::ServiceAccount
    roles:
      - editor
